"""changed column names

Revision ID: 12006d8faf14
Revises: d0d6a106cf88
Create Date: 2024-03-31 22:49:04.219479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12006d8faf14'
down_revision = 'd0d6a106cf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=10), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
