"""added admin to inherit from user

Revision ID: b9d68a1598ce
Revises: c3d317601945
Create Date: 2024-03-28 18:08:54.208298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d68a1598ce'
down_revision = 'c3d317601945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_admin_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='fk_admins_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###
