"""mispelling

Revision ID: f577b578efa9
Revises: ee8b3e7adc25
Create Date: 2024-03-20 21:34:57.057195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f577b578efa9'
down_revision = 'ee8b3e7adc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speciality', sa.String(), nullable=True))
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('speciality')

    # ### end Alembic commands ###
